# 驱动配置信息  
spring: 
  datasource:
    type : com.alibaba.druid.pool.DruidDataSource  
    url : jdbc:mysql://47.100.207.19:3306/demo?userSSL=false&characterEncoding=UTF8&serverTimezone=UTC  
    username: demo  
    password: 123456
    driverClassName : com.mysql.cj.jdbc.Driver  
  redis:
    shiro:
      host: 47.100.207.19
      port: 6379
      timeout: 3000
      password: dy513952310
    open: false  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: 47.100.207.19
    port: 6379
    timeout: 3000
    password: dy513952310  # 连接超时时长（毫秒）
    jedis: 
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接